# Day 01

### 1. Even and odd
a. Write the code using np.arrange() to get all even numbers between 21 and 70, (70 inclusive)

b. Write code using np.arrange() to get all odd numbers between 20 and 71. (71 inclusive)

In [2]:
import numpy as np
arr = np.arange(22, 71, 2)
print(arr)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]


In [3]:
arr = np.arange(21, 72, 2)
print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


### 2. Cast a type

Raghu has created a numpy arr using the following code:

`import numpy as np`

`arr = np.array([10, 20, 30, 40, 50])`

He wants to change the data type from integer to float

In [5]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr.astype('float64')

array([10., 20., 30., 40., 50.])

### 3. Slice away
what would be the output of following code

In [12]:
import numpy as np
a = np.arange(10)
print(a[2:5]) # 2, 3, 4

[2 3 4]


### 4. What about output
which option is correct about output of the following code snippet

In [16]:
import numpy as np
x = np.array([-5, 9, 20, 25, -3, 5, 16, 10, -8])
x[(x >= -5) &(x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10  -8]


### 5.Comparison Return!
what will be the output of the following code?

In [17]:
a = np.array([100, 200, 300, 400])
b = np.array([300, 200, 100, 400])

print(a==b)

[False  True False  True]


### 6. The dawn of the planet of numpy

#### Problem Statement:
Given the start, end, and the stepsize return a numpy array sequence in given range with the specified stepsize

#### Input Format:
One line of input will have 3 space-separated integers consisting of start, end, and step

#### Output Format:
A numpy array with elements rounded off to 2 decimal places

In [18]:
import numpy as np
def create_seq(start, end, step):
    arr = np.round(np.arange(start, end, step))
    return(arr)

create_seq(10, 30, 2)


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### 7. Index of Pokedex
#### Problem Statement:
Give a 1D array, return the first and last element of the array

#### Input Format:
A 1D numpy array

#### Output Format:
A tuple (first element, last element)

In [20]:
import numpy as np  
def get_firt_last(arr: np.ndarray):
    return (arr[0], arr[-1])

a = np.array([1, 2, 3, 4, 5])
get_firt_last(a)

(1, 5)

### 8.Index operation
What would be the output of the following code:

`import numpy as np`

`arr = np.array([1, 2, 3, 4])`

`print(arr[2] + arr[-2])`

In [23]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[-2]) # 6 (3+3)

6


### 9.Create the Sequence 
Create a Sequence of a given length from a given start point, where the difference between the 2 consecutive elements of the expected sequence is also given as step

In [25]:
import numpy as np
def seq(start, length, step):
    return np.arange(start, start+(length*step), step)
    
seq(5, 10, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

### 10. Shape of you
Given an array, return the shape and dimensions of the array.

In [28]:
import numpy as np
def get_arr_props(arr: np.ndarray):
    return arr.shape, arr.ndim, arr.dtype

a = np.array([1, 2, 3])
get_arr_props(a)

((3,), 1, dtype('int32'))