# DAY 02
### 1. What about code?
In the below code, `condition` implies the situation that `arr` has `at least one value smaller than or equal to 0.6`  

In [3]:
import numpy as np
arr = 2 * np.arange(0, 2, 0.5)
if arr.all() <= 0.6:
    print('condition satifies')
else:
    print('condition does not satify')

condition satifies


### 2. What will be printed?


In [9]:
import numpy as np
x = np.array([[200, 200, 200],[300, 300,300], [400, 400, 400]])
v = np.array([200, 300, 400])
print((x/v[:, None]))[1][1] # throws TypeError

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


TypeError: 'NoneType' object is not subscriptable

In [10]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p+q)[1][1])

21


### 3. Batchmate's code
What will be the output of following code

In [11]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])

x = np.transpose(a).reshape(2, 3)
print(x.flatten())

[16 81 33  5  6  1]


### 4. The Mask
#### Problem Statement:
Given an array of marks, return the array only containing elements with marks > 40

In [13]:
import numpy as np
def filter_marks(marks: np.ndarray) :
    mask = marks > 40
    return marks[mask]

marks = np.array([100, 35, 68, 90, 100])
filter_marks(marks)

array([100,  68,  90, 100])

### 5. Indexed array
Given the following code, what will be the output

In [15]:
import numpy as np
a = np.array([[34, 28, 55], [8, 56, 3], [77, 87, 19]])

print(a.transpose()[-2, -2])

56


### 6. One for All
#### Problem Statement:
Given a numpy array and traget values k,  return True if all elements of the array satisfy the given condition
* Multiple of 2
* Greater than k

In [ ]:
import numpy as np
def check_conditions(arr: np.ndarray, k:int):
    mask = (arr % 2 == 0) & (arr > k)
    return arr.all(mask)