In [3]:
import numpy as np

## Create a Numpy ndarray object  

In [4]:
# checking numpy version
print(np.__version__)

1.25.2


In [5]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


## Dimensions in Arrays

In [7]:
# 0-D Arrays
arr = np.array(42)

print(arr)

42


In [8]:
# 1-D Arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [9]:
# 2-D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
# 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]]


In [20]:
a = np.array(45)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5,6]],[[1, 2, 3], [4, 5, 6]]])

print(a.ndim, b.ndim, c.ndim, d.ndim ,end=" Dimesions", sep=" Dimesion\n")

0 Dimesion
1 Dimesion
2 Dimesion
3 Dimesions

## Higher Dimensional Array

In [21]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)

print(arr)
print('number of dimensions: ', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions:  5


## Numpy Array Indexing

In [24]:
# Accessing the Array Elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[0]) # first element
print(arr[1]) # second element

1
2


In [26]:
print(arr[1] + arr[2]) # adding second element and third element

5


### Access 2-D Arrays

In [30]:
arr = np.array([[1, 2, 3, 4, 5], [7, 8, 9, 10, 11]])
print('2nd element on 1st row:', arr[0, 1])

2nd element on 1st row: 2


In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('5th element on 2nd row:', arr[1, 2])

5th element on 2nd row: 6


In [36]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8,9]]])

print(arr[0, 1, 2])

6


### Negitive Indexing 

In [38]:
arr = np.array([[1, 2, 3,4, 5], [6, 7, 8, 9, 10]])

print('Last element from 2nd dim:', arr[1, -1])

Last element from 2nd dim: 10


## Numpy Array Slicing

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
print(arr[1:5])

# Note : The result includes the start index, but excludes the end index

[2 3 4 5]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[4:])

[5 6 7 8 9]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[:4])

[1 2 3 4]


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[-3:-1])

[7 8]


In [44]:
# step
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[1:5:2])

[2 4]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[::2])

[1 3 5 7 9]
